theme = "harbor"
baseURL = "https://allaway.netlify.app"
title = "robert's blog"
author = "Robert Allaway"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
  name = "Robert Allaway"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder fa-lg"
  url = "categories"
  weight = 3
  
[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "twitter"
  name = "Twitter"
  icon = "fab fa-twitter fa-lg"
  url = "https://www.twitter.com/allawayr"
  weight = 3
  
[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"
    
